[package]
name = "grasp"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty_assertions = "1.4.1"
serde = { version = "1.0", features = ["derive"], optional = true}
serde_json = { version = "1.0", optional = true }

[features]
serde = ["dep:serde", "dep:serde_json"]
