[package]
name = "grasp-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "grasp"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
grasp-core = { path = "../grasp-core" }