[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", optional = true, features = ["full"] }
quote = { version = "1.0", optional = true }

[features]
meta = ["dep:syn", "dep:quote"]